### ISSUE TITLE
Error: Cannot find module '../../../lib/util'

### ISSUE THREAD

**Issue by weyert** [trailsjs/generator-trails#3]
After install this module and trying to run `yo trails` I am getting the following:

```
MacBook-Pro trails # yo trails
module.js:538
    throw err;
    ^

Error: Cannot find module '../../../lib/util'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/develop/.nvm/versions/node/v8.9.3/lib/node_modules/generator-trails/generators/app/steps/writing.js:5:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by elenduuche** [comment]
Encountered the same issue today.

**Comment by tjwebb** [comment]
Resolving this today, this was an issue in the `3.0.0-pre3` release that we never followed up with a major version release. Sorry for the inconvenience.

**Comment by weyert** [comment]
Thank you Travis :)

**Comment by hendratommy** [comment]
Any update regarding this issue?
