### ISSUE TITLE
generator-trails@1.0.11 crashes during scaffolding

### ISSUE THREAD

**Issue by wbprice** [trailsjs/generator-trails#54]
On OSX v10.11.4 (15E65) `generator-trails@1.0.11` crashes during scaffolding.  My selections were:

```sh
? Choose a Web Server hapi
? Choose an ORM waterline
? Do you want to use Footprints (automatic REST API from models) ? Yes
? Module Name (test-trails-generator)
```
Stack trace:
```sh
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/lib/base.js:232:45)
    at askName (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/inquirer-npm-name/lib/index.js:25:19)
    at module.exports.generators.Base.extend.prompting.askForModuleName (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/generators/app/index.js:112:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jaumard** [comment]
What's is your `yo` version ? Try the latest please, I'm on mac too and have no problem

**Comment by jaumard** [comment]
```
mac:testTrails jaumard$ yo trails

Get ready to blaze a new Trails Application!

Checking for updates...
? Choose a Web Server hapi
? Choose an ORM waterline
? Do you want to use Footprints (automatic REST API from models) ? Yes
? Module Name test-trails
? Description 
? Project homepage url 
? Author's Name jaumard
? Author's Email jimmy.aumard@gmail.com
? Author's Homepage 
? Package keywords (comma to split) 
? GitHub username or organization 
? Which license do you want to use? MIT
   create package.json
identical .editorconfig
identical .gitignore
   create api/services/DefaultService.js
   create api/services/index.js
   create api/models/index.js
   create config/database.js
   create config/env/development.js
   create config/env/index.js
   create config/env/production.js
   create config/env/staging.js
   create config/env/testing.js
   create config/i18n.js
   create config/index.js
   create config/locales/en.json
   create config/log.js
   create config/main.js
   create config/policies.js
   create config/routes.js
   create config/session.js
   create config/views.js
   create index.js
   create server.js
   create api/index.js
   create LICENSE
...
```

**Comment by wbprice** [comment]
@jaumard I updated the `yo` package and everything worked.  Thanks!
