### ISSUE TITLE
Generator trails fails to install when behind corporate proxy

### ISSUE THREAD

**Issue by animedbz16** [trailsjs/generator-trails#60]
I've had a little bit more time to investigate this which I orginally reported here:
https://github.com/trailsjs/trails/issues/210

When dumping the options that are passed into the got library, it seems that this generator module is attempting to directly call out to npm itself for installation, which doesn't use my proxy environment.

```
[user@localhost trails-app]$ yo trails

Get ready to blaze a new Trails Application!

Checking for updates...
? Choose a Web Server express
? What express version do you want to use ? 5
? Choose an ORM mongoose
? Do you want to use Footprints (automatic REST API from models) ? Yes
? Module Name trails-app
Opts =>  { protocol: 'https:',
  path: '/trails-app',
  retries: [Function: backoff],
  slashes: true,
  auth: null,
  host: 'registry.npmjs.org',
  port: null,
  hostname: 'registry.npmjs.org',
  hash: null,
  search: null,
  query: null,
  pathname: '/trails-app',
  href: 'https://registry.npmjs.org/trails-app',
  method: 'HEAD',
  headers: 
   { 'user-agent': 'got/6.3.0 (https://github.com/sindresorhus/got)',
     'accept-encoding': 'gzip,deflate' },
  followRedirect: true }


RequestError: socket hang up
    at ClientRequest.req.once.err (/home/user/.nvm/versions/node/v6.3.0/lib/node_modules/generator-trails/node_modules/npm-name/node_modules/got/index.js:67:21)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

events.js:160
      throw er; // Unhandled 'error' event
      ^
RequestError: socket hang up
    at ClientRequest.req.once.err (/home/user/.nvm/versions/node/v6.3.0/lib/node_modules/generator-trails/node_modules/npm-name/node_modules/got/index.js:67:21)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jaumard** [comment]
This part is done by https://github.com/trailsjs/generator-node maybe the original repo have a fix for it that can we use too

**Comment by animedbz16** [comment]
Closing this out here since I created a new issue in the other repo.
