### ISSUE TITLE
how did i break this?

### ISSUE THREAD

**Issue by connor11528** [trailsjs/generator-trails#61]
Hey errybody. What did I do wrong here? Generated a new trails app, got an error. Please see below!

```
yo trails

     _-----_
    |       |    .------------------------------------------.
    |--(o)--|    | Update available: 1.7.0 (current: 1.6.0) |
   `---------´   |     Run npm install -g yo to update.     |
    ( _´U`_ )    '------------------------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 


Get ready to blaze a new Trails Application!

Checking for updates...
? Choose a Web Server express
? What express version do you want to use ? 4
? Choose an ORM waterline
? Do you want to use Footprints (automatic REST API from models) ? Yes
? Module Name (trails-tutorial) 

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/lib/base.js:232:45)
    at askName (/usr/local/lib/node_modules/generator-trails/node_modules/inquirer-npm-name/lib/index.js:25:19)
    at module.exports.generators.Base.extend.prompting.askForModuleName (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/generators/app/index.js:112:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-trails/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-trails/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-trails/node_modules/@trails/generator-node/node_modu%            
```

**Comment by jaumard** [comment]
We only are compatible with the last `yo` I think it's 1.8 (maybe 1.7 don't remember) :)

**Comment by connor11528** [comment]
Yes okay. `npm i -g yo` solved this issue!
